### ISSUE TITLE
Workspace setup failed

### ISSUE THREAD

**Issue by Byllfighter** [Goldorion/MCreatorFabricGenerator#268]
### Issue description

Setup of my Workspace failed with fabric 1.19.2 generator
```
Executing Gradle task: tasks genSourcesWithCfr
Build info: MCreator 2022.2.34517, fabric-1.19.2, 64-bit, 16320 MB, Windows 10, JVM 17.0.3, JAVA_HOME: D:\Pylo\MCreator 2022.2\jdk, started on: 2022-09-22-10:29:58
 
> Configure project :
Fabric Loom: 1.0.7
:remapping 40 mods from modImplementation
:remapping sources
Not publishing sources jar as it was not found. Use java.withSourcesJar() to fix.
> Task :tasks
------------------------------------------------------------
Tasks runnable from root project 'partygui'
------------------------------------------------------------
Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.
Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.
Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.
Fabric tasks
------------
configureClientLaunch - Setup the required files to launch the Minecraft client
configureLaunch - Setup the required files to launch Minecraft
downloadAssets - Downloads required game assets for Minecraft.
generateDLIConfig - Generate the DevLaunchInjector config file
generateLog4jConfig - Generate the log4j config file
generateRemapClasspath - Generate the remap classpath file
genSources - Decompile minecraft using the default decompiler.
genSourcesWithCfr - Decompile minecraft using Cfr.
genSourcesWithFernFlower - Decompile minecraft using FernFlower.
ideaSyncTask
migrateMappings - Migrates mappings to a new version.
prepareRemapJar
remapJar - Remaps the built project jar to intermediary mappings.
remapSourcesJar - Remaps the default sources jar to intermediary mappings.
runClient - Starts the 'null' run configuration
runServer - Starts the 'null' run configuration
Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'partygui'.
dependencies - Displays all dependencies declared in root project 'partygui'.
dependencyInsight - Displays the insight into a specific dependency in root project 'partygui'.
help - Displays a help message.
javaToolchains - Displays the detected java toolchains.
outgoingVariants - Displays the outgoing variants of root project 'partygui'.
projects - Displays the sub-projects of root project 'partygui'.
properties - Displays the properties of root project 'partygui'.
tasks - Displays the tasks runnable from root project 'partygui'.
IDE tasks
---------
cleanEclipse - Cleans all Eclipse files.
cleanEclipseRuns - Removes Eclipse run configurations for this project.
cleanIdea - Cleans IDEA project files (IML, IPR)
eclipse - Generates all Eclipse files.
genEclipseRuns - Generates Eclipse run configurations for this project.
genIdeaWorkspace - Generates an IntelliJ IDEA workspace from this project.
idea - Generates IDEA project files (IML, IPR, IWS)
openIdea - Opens the IDEA project
vscode - Generates VSCode launch configurations.
Verification tasks
------------------
check - Runs all checks.
test - Runs the test suite.
validateAccessWidener - Validate all the rules in the access widener against the Minecraft jar
Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
To see all tasks and more detail, run gradle tasks --all
To see more detail about a task, run gradle help --task <task>
> Task :validateAccessWidener NO-SOURCE
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
Could not write standard input to Gradle Worker Daemon 1.
java.io.IOException: Идет закрытие канала
 at java.base/java.io.FileOutputStream.writeBytes(Native Method)
 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:68)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833 at java.base/java.lang.Thread.run(Thread.java:833)
> Task :genSourcesWithCfr FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':genSourcesWithCfr'.
> There was a failure while executing work items
 > A failure occurred while executing net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction
  > Failed to run Gradle Worker Daemon
  > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 5s
2 actionable tasks: 2 executed
 
BUILD FAILED
Task completed in 1 minute and 6 seconds
```

### How to reproduce this issue?

Create a new Workspace

### Operating system

Windows

### Details

MCreator 2022.2
fabric-1.19.2

### Issue tracker rule checks (please read carefully)

- [x] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Try to re-run the setup. I am not able to reproduce the issue.
