### ISSUE TITLE
:genSourcesWithCfr fails to execute

### ISSUE THREAD

**Issue by voided-ptr** [Goldorion/MCreatorFabricGenerator#482]
### Issue description

It happens every time i try to create a fabric mod.
Creating a blank workspace also doesn't work

### How to reproduce this issue?

1. just create a workspace or port forge workspace to fabric
2. error appears

### Operating system

Windows

### Details

MCreator version: 2023.3
Generator: fabric-1.20.1 (1.9.10)

### Logs

```Executing Gradle task: tasks genSourcesWithCfr
Build info: MCreator 2023.3.36712, fabric-1.20.1, 64-bit, 32049 MB, Windows 11, JVM 17.0.7, JAVA_HOME: E:\Program Files\Pylo\MCreator\jdk, started on: 2023-11-06-15:14:10
 
> Configure project :
Fabric Loom: 1.4.4
> Task :tasks
------------------------------------------------------------
Tasks runnable from root project 'parry_this'
------------------------------------------------------------
Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the classes of the 'main' feature.
sourcesJar - Assembles a jar archive containing the main sources.
testClasses - Assembles test classes.
Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.
Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the 'main' feature.
Fabric tasks
------------
configureClientLaunch - Setup the required files to launch the Minecraft client
configureLaunch - Setup the required files to launch Minecraft
downloadAssets - Downloads required game assets for Minecraft.
generateDLIConfig - Generate the DevLaunchInjector config file
generateLog4jConfig - Generate the log4j config file
generateRemapClasspath - Generate the remap classpath file
genSources - Decompile minecraft using the default decompiler.
genSourcesWithCfr - Decompile minecraft using Cfr.
genSourcesWithFernFlower - Decompile minecraft using FernFlower.
genSourcesWithVineflower - Decompile minecraft using Vineflower.
ideaSyncTask
migrateMappings - Migrates mappings to a new version.
remapJar - Remaps the built project jar to intermediary mappings.
remapSourcesJar - Remaps the default sources jar to intermediary mappings.
runClient - Starts the 'null' run configuration
runServer - Starts the 'null' run configuration
Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'parry_this'.
dependencies - Displays all dependencies declared in root project 'parry_this'.
dependencyInsight - Displays the insight into a specific dependency in root project 'parry_this'.
help - Displays a help message.
javaToolchains - Displays the detected java toolchains.
outgoingVariants - Displays the outgoing variants of root project 'parry_this'.
projects - Displays the sub-projects of root project 'parry_this'.
properties - Displays the properties of root project 'parry_this'.
resolvableConfigurations - Displays the configurations that can be resolved in root project 'parry_this'.
tasks - Displays the tasks runnable from root project 'parry_this'.
IDE tasks
---------
cleanEclipse - Cleans all Eclipse files.
cleanEclipseRuns - Removes Eclipse run configurations for this project.
cleanIdea - Cleans IDEA project files (IML, IPR)
eclipse - Generates all Eclipse files.
genEclipseRuns - Generates Eclipse run configurations for this project.
genIdeaWorkspace - Generates an IntelliJ IDEA workspace from this project.
idea - Generates IDEA project files (IML, IPR, IWS)
openIdea - Opens the IDEA project
vscode - Generates VSCode launch configurations.
Verification tasks
------------------
check - Runs all checks.
test - Runs the test suite.
validateAccessWidener - Validate all the rules in the access widener against the Minecraft jar
Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
To see all tasks and more detail, run gradle tasks --all
To see more detail about a task, run gradle help --task <task>
> Task :validateAccessWidener NO-SOURCE
Could not write standard input to Gradle Worker Daemon 1.
java.io.IOException: Идет закрытие канала
 at java.base/java.io.FileOutputStream.writeBytes(Native Method)
 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349 at java.base/java.io.FileOutputStream.write(FileOutputStream.java:349)
 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81 at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142 at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.writeBuffer(ExecOutputHandleRunner.java:98 at org.gradle.process.internal.streams.ExecOutputHandleRunner.writeBuffer(ExecOutputHandleRunner.java:98)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:85 at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:85)
 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:64 at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:64)
 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64 at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
 at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47 at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.lang.Thread.run(Thread.java:833 at java.base/java.lang.Thread.run(Thread.java:833)
> Task :genSourcesWithCfr FAILED
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':genSourcesWithCfr'.
> There was a failure while executing work items
 > A failure occurred while executing net.fabricmc.loom.task.GenerateSourcesTask$DecompileAction
  > Failed to run Gradle Worker Daemon
  > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 21s
2 actionable tasks: 2 executed
 
BUILD FAILED
Task completed in 21 seconds
```

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/MCreator/MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by voided-ptr** [comment]
Even a fresh installation of MCreator doesn't solve the problem

**Comment by Goldorion** [comment]
Hi, (sorry for the delay) did you try to use the button to retry the workspace's creation? Sometimes it fixes the problem. I already had similar problems when developing the plugin and just re-testing without closing the workspace fixed the problem for some reason. I don't know what's causing this issue.

**Comment by voided-ptr** [comment]
I tried retrying but the error persists and I moved from mcreator to making multiplatform mods myself about 2.5 months ago so I can't recreate it at the moment

**Comment by Kray2OI9** [comment]
what should I do with the **bug**?
