### ISSUE TITLE
[Bug] fail to compile

### ISSUE THREAD

**Issue by Armagedon13** [Goldorion/MCreatorFabricGenerator#84]
**Describe the bug**

**Log**

 
```
Executing Gradle task: runClient 
Build info: MCreator 2020.5.46519, fabric-1.16.3, 64-bit, 8191 MB, Windows 10, JVM 1.8.0_265, JAVA_HOME: D:\Program Files\Pylo\MCreator\jdk 
> Configure project : 
Fabric Loom: 0.4.33 Build(jenkins #33) 
:setting up loom dependencies 
:setting up mappings (yarn 1.16.3+build.1) 
Configuring compiler arguments for Java 
> Task :downloadAssets 
:downloading assets... 
> Task :compileJava 
2020-11-15 10:45:30,337 Daemon worker Thread 2 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 
Note: SpongePowered MIXIN Annotation Processor Version=0.8.2 
Note: ObfuscationServiceFabric supports type: "official:intermediary" 
Note: ObfuscationServiceFabric supports type: "official:named" 
Note: ObfuscationServiceFabric supports type: "intermediary:official" 
Note: ObfuscationServiceFabric supports type: "intermediary:named" 
Note: ObfuscationServiceFabric supports type: "named:official" 
Note: ObfuscationServiceFabric supports type: "named:intermediary" 
Note: ObfuscationServiceMCP supports type: "searge" 
Note: ObfuscationServiceMCP supports type: "notch" 
> Task :processResources 
> Task :classes 
> Task :jar 
> Task :runClient 
10:45.37 [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.3 
10:45.38 main/INFO (Fabric|Loader) FabricLoader Loading 43 mods: fabric-renderer-api-v1@0.3.0+8bcfced895, fabric-screen-handler-api-v1@1.1.0+8724984195, minecraft@1.16.3, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, fabric-keybindings-v0@0.2.0+3fa9f7c595, modmenu@1.14.6+build.31, fabric-command-api-v1@1.0.8+5ce5339895, fabricloader@0.10.5+build.213, fabric-tool-attribute-api-v1@1.2.2+ccce563e95, fabric-structure-api-v1@1.0.1+fb0d9b0e95, fabric-renderer-indigo@0.4.0+8bcfced895, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.8.0+c1aa8ed895, fabric-events-interaction-v0@0.4.0+e2e6cdad95, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-item-api-v1@1.1.0+29679fd695, fabric-game-rule-api-v1@1.0.1+74685c1495, fabric-api-base@0.1.3+12a8474c95, fabric-rendering-v0@1.1.0+5341049095, fabric-rendering-v1@1.3.0+432ea18895, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-textures-v0@1.0.4+eae12eb895, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-biome-api-v1@2.0.0+c29459ab95, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e95, fabric-registry-sync-v0@0.5.0+c1aa8ed895, fabric-commands-v0@0.2.0+52d3083695, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-renderer-registries-v1@2.1.0+e2862de695, asd@1.0.0, fabric-loot-tables-v1@1.0.1+432ea18895, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, fabric@0.21.0+build.407-1.16, fabric-item-groups-v0@0.2.0+438f963695, fabric-models-v0@0.1.0+dfdb52d695, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-networking-v0@0.1.10+e00ecb5f95, fabric-object-builders-v0@0.7.0+432ea18895 
10:45.38 [main/WARN] (Fabric|Loader) Runtime mod remapping disabled due to no fabric.remapClasspathFile being specified. You may need to update loom. 
10:45.38 main/INFO (mixin) SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C./Users/ulymc/.mcreator/gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.8.2+build.24/e5a741445d0f425bf3cce946c6cf8c7fb8376b2/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT 
10:45.39 [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper! 
Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modid.mixins.json 
   at org.spongepowered.asm.mixin.transformer.Config.create(
Config.java:153
   at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) 
   at org.spongepowered.asm.mixin.Mixins.createConfiguration(
Mixins.java:100
   at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) 
   at org.spongepowered.asm.mixin.Mixins.addConfiguration(
Mixins.java:87
   at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) 
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(
FabricMixinBootstrap.java:44
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44) 
   at java.lang.Iterable.forEach(
Iterable.java:75
   at java.lang.Iterable.forEach(Iterable.java:75) 
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(
FabricMixinBootstrap.java:83
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83) 
   at net.fabricmc.loader.launch.knot.Knot.init(
Knot.java:133
   at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:133) 
   at net.fabricmc.loader.launch.knot.KnotClient.main(
KnotClient.java:26
   at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) 
   at net.fabricmc.devlaunchinjector.Main.main(
Main.java:86
   at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) 
Caused by: java.lang.IllegalArgumentException: The specified resource 'modid.mixins.json' was invalid or could not be read 
   at org.spongepowered.asm.mixin.transformer.MixinConfig.create(
MixinConfig.java:1090
   at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1090) 
   at org.spongepowered.asm.mixin.transformer.Config.create(
Config.java:148
   at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) 
   ... 8 more 
> Task :runClient FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':runClient'. 
> Process 'command 'D:\Program Files\Pylo\MCreator\jdk\bin\java.exe'' finished with non-zero exit value 1 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. 
Use '--warning-mode all' to show the individual deprecation warnings. 
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings 
BUILD FAILED in 25s 
5 actionable tasks: 5 executed 
BUILD FAILED 
Task completed in 25670 milliseconds 
```

**Affected version(s)** Release/Snapshot X.X.X+foo
mcreator 2020.5 and 2020.4 
and last generator-fabric 1.16.3

**To Reproduce**
1. create new workspace
2. Click on buld
3. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem

**Additional context**

**Comment by Anders-1** [comment]
Same thing is happening to me.

**Comment by BoogieMonster1O1** [comment]
Fixed in the 1.17 branch

For 1.16, a quick fix would be to edit the fabric.mod.json inside src/main/resources and remove the

"mixins": [
  "modid.mixins.json"
]
part
and if there's a comma before "mixins", remove that too

i will be pushing a fix to the 1.16 branch soon

**Comment by Anders-1** [comment]
I am really new to MCreator so I don't really get what to do. Can you explain it again? Also what are the 1.17 and 1.16 branches? Thanks!

**Comment by Anders-1** [comment]
I think I figured out how to fix it, but can you please still explain what the 1.17 and 1.16 branches are? Thanks!

**Comment by Blackout03** [comment]
for the different minecraft versions

**Comment by Anders-1** [comment]
Ok, but how can they make a 1.17 version if 1.17 is not out yet?

**Comment by BoogieMonster1O1** [comment]
> Ok, but how can they make a 1.17 version if 1.17 is not out yet?

1.17 snapshots are out

**Comment by Anders-1** [comment]
Oh, so you can make the 1.17 Fabric Generator based on snapshots? Cool!

**Comment by Anders-1** [comment]
I tried editing the file in src/main/resources to fix the problem but it didn't work, I might have not done it correctly though.
