### ISSUE TITLE
uh... start testing error?

### ISSUE THREAD

**Issue by Meganobody** [Goldorion/MCreatorFabricGenerator#96]
i make mod, with this generator
but when i want to test my mod i have this error

16:12.09 [main/INFO] (FabricLoader) Loading for game Minecraft 1.16.3 
16:12.12 main/INFO (Fabric|Loader) FabricLoader Loading 43 mods: minecraft@1.16.3, fabric-screen-handler-api-v1@1.1.0+8724984195, fabric-renderer-api-v1@0.3.0+8bcfced895, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, fabric-keybindings-v0@0.2.0+3fa9f7c595, modmenu@1.14.6+build.31, fabric-command-api-v1@1.0.8+5ce5339895, fabricloader@0.10.5+build.213, better_vanila_food@1.0.0, fabric-tool-attribute-api-v1@1.2.2+ccce563e95, fabric-renderer-indigo@0.4.0+8bcfced895, fabric-structure-api-v1@1.0.1+fb0d9b0e95, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.8.0+c1aa8ed895, fabric-item-api-v1@1.1.0+29679fd695, fabric-events-interaction-v0@0.4.0+e2e6cdad95, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-game-rule-api-v1@1.0.1+74685c1495, fabric-api-base@0.1.3+12a8474c95, fabric-rendering-v0@1.1.0+5341049095, fabric-rendering-v1@1.3.0+432ea18895, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d95, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-textures-v0@1.0.4+eae12eb895, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e95, fabric-biome-api-v1@2.0.0+c29459ab95, fabric-registry-sync-v0@0.5.0+c1aa8ed895, fabric-commands-v0@0.2.0+52d3083695, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-renderer-registries-v1@2.1.0+e2862de695, fabric-loot-tables-v1@1.0.1+432ea18895, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, fabric@0.21.0+build.407-1.16, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-item-groups-v0@0.2.0+438f963695, fabric-models-v0@0.1.0+dfdb52d695, fabric-object-builders-v0@0.7.0+432ea18895, fabric-networking-v0@0.1.10+e00ecb5f95 
16:12.12 [main/WARN] (Fabric|Loader) Runtime mod remapping disabled due to no fabric.remapClasspathFile being specified. You may need to update loom. 
16:12.13 main/INFO (mixin) SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C./Users/HP/.mcreator/gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.8.2+build.24/e5a741445d0f425bf3cce946c6cf8c7fb8376b2/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT 
16:12.13 [main/INFO] (Fabric|MixinBootstrap) Loaded Fabric development mappings for mixin remapper! 
Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config modid.mixins.json 
   at org.spongepowered.asm.mixin.transformer.Config.create(
Config.java:153
   at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153) 
   at org.spongepowered.asm.mixin.Mixins.createConfiguration(
Mixins.java:100
   at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100) 
   at org.spongepowered.asm.mixin.Mixins.addConfiguration(
Mixins.java:87
   at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87) 
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(
FabricMixinBootstrap.java:44
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44) 
   at java.lang.Iterable.forEach(
Iterable.java:75
   at java.lang.Iterable.forEach(Iterable.java:75) 
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(
FabricMixinBootstrap.java:83
   at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83) 
   at net.fabricmc.loader.launch.knot.Knot.init(
Knot.java:133
   at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:133) 
   at net.fabricmc.loader.launch.knot.KnotClient.main(
KnotClient.java:26
   at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) 
   at net.fabricmc.devlaunchinjector.Main.main(
Main.java:86
   at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) 
Caused by: java.lang.IllegalArgumentException: The specified resource 'modid.mixins.json' was invalid or could not be read 
   at org.spongepowered.asm.mixin.transformer.MixinConfig.create(
MixinConfig.java:1090
   at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1090) 
   at org.spongepowered.asm.mixin.transformer.Config.create(
Config.java:148
   at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148) 
   ... 8 more 
> Task :runClient FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':runClient'. 
> Process 'command 'C:\Users\[user]\Desktop\���������\MCreator\jdk\bin\java.exe'' finished with non-zero exit value 1 
* Try: 
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights. 
* Get more help at https://help.gradle.org 
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0. 
Use '--warning-mode all' to show the individual deprecation warnings. 
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings 
BUILD FAILED in 1m 52s 
5 actionable tasks: 4 executed, 1 up-to-date 
BUILD FAILED 
Task completed in 118613 milliseconds

**Comment by Goldorion** [comment]
Use the latest version with the latest snapshot.
